### Index İle Elemana Erişmek

In [2]:
import numpy as np

In [3]:
m = np.random.randint (10,size =(3,5))

In [4]:
m


array([[3, 7, 9, 0, 1],
       [2, 3, 9, 1, 5],
       [9, 0, 5, 5, 3]])

In [6]:
m[1,2]

9

In [7]:
m[2,4]

3

In [11]:
m[1,0] = 3.3

In [13]:
m   #randint fonksiyonu

array([[3, 7, 9, 0, 1],
       [3, 3, 9, 1, 5],
       [9, 0, 5, 5, 3]])

#### Array Alt Küme İşlemleri (Slicing)

In [16]:
a = np.arange(20,30)

In [19]:
a [0:6] #0. indexten başla 6. indexe kadar git.

array([20, 21, 22, 23, 24, 25])

In [20]:
a[:9]

array([20, 21, 22, 23, 24, 25, 26, 27, 28])

In [22]:
a[1::3] #1. indexten başla 3'er atlayarak git.

array([21, 24, 27])

##### iki boyut

In [26]:
m = np.random.randint(10,size=(5,5))

In [27]:
m

array([[9, 7, 1, 4, 2],
       [5, 9, 6, 9, 9],
       [0, 2, 9, 4, 7],
       [9, 8, 4, 8, 4],
       [9, 5, 0, 7, 7]])

In [28]:
m [0:3,0:3]

array([[9, 7, 1],
       [5, 9, 6],
       [0, 2, 9]])

In [29]:
m[:,1:3]

array([[7, 1],
       [9, 6],
       [2, 9],
       [8, 4],
       [5, 0]])

In [30]:
m [:2,:]

array([[9, 7, 1, 4, 2],
       [5, 9, 6, 9, 9]])

#### Alt Küme Üzerinde İşlem Yapmak 

In [34]:
alt_kume = m[1:4,1:4]

In [35]:
alt_kume

array([[9, 6, 9],
       [2, 9, 4],
       [8, 4, 8]])

In [36]:
alt_kume[1,1] = 5

In [37]:
alt_kume

array([[9, 6, 9],
       [2, 5, 4],
       [8, 4, 8]])

In [38]:
m

array([[9, 7, 1, 4, 2],
       [5, 9, 6, 9, 9],
       [0, 2, 5, 4, 7],
       [9, 8, 4, 8, 4],
       [9, 5, 0, 7, 7]])

Yapılan değişiklik m arrayini de etkiledi.  Ancak sadece alt küme üzerinde yapılmak istenirse "copy ()" fonksiyonu kullanılır.

In [47]:
alt_kume = m[1:4,1:4].copy()

In [48]:
alt_kume

array([[9, 6, 9],
       [2, 5, 4],
       [8, 4, 8]])

In [50]:
alt_kume[0,0] = 5

In [51]:
alt_kume

array([[5, 6, 9],
       [2, 5, 4],
       [8, 4, 8]])

In [52]:
m

array([[9, 7, 1, 4, 2],
       [5, 9, 6, 9, 9],
       [0, 2, 5, 4, 7],
       [9, 8, 4, 8, 4],
       [9, 5, 0, 7, 7]])

Değişlik sadece alt_kume üzerinde oldu ve m arrayi ilk halinde 

#### Fancy Metodu İle Elemanlara Erişmek

In [55]:
v = np.arange(0,30,3)

In [56]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [57]:
v[1]

3

In [58]:
v[2]

6

In [59]:
fancy  = [1,2]
v[fancy]

array([3, 6])

##### iki boyut

In [60]:
m = np.arange(9).reshape(3,3)

In [61]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
satır = np.array([0,1])
sütun = np.array ([1,2])

In [65]:
m[satır,sütun]

array([1, 5])

### Koşullu Eleman İşlemleri

In [66]:
v = np.array([1,2,3,4,5,6])

In [67]:
v<3

array([ True,  True, False, False, False, False])

In [68]:
v[v<3]

array([1, 2])

In [69]:
v**2

array([ 1,  4,  9, 16, 25, 36], dtype=int32)

In [70]:
v*2

array([ 2,  4,  6,  8, 10, 12])

In [71]:
v[v!=3]

array([1, 2, 4, 5, 6])

#### Matematiksel İşlemler

In [74]:
np.subtract(v,1)

array([0, 1, 2, 3, 4, 5])

In [75]:
np.add(v,1)

array([2, 3, 4, 5, 6, 7])

In [76]:
np.multiply(v,2)

array([ 2,  4,  6,  8, 10, 12])

In [80]:
np.mod(v,5) #=v%2

array([1, 2, 3, 4, 0, 1], dtype=int32)

In [79]:
np.power(v,3)  # = v**3

array([  1,   8,  27,  64, 125, 216], dtype=int32)