#### NumPy Array Oluşturmak

In [2]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
type(a)

numpy.ndarray

In [6]:
b = np.array([1.2,3,5,6])
b

array([1.2, 3. , 5. , 6. ])

Numpy kütüphanesinin tip baskınlığı söz konusudur. int değerlerde olmasına rağmen tüm değerler float olarak yazılmıştır.


In [9]:
b = np.array([1.2,3,5,6],dtype = "int")
b

array([1, 3, 5, 6])

dtype ile tip bilgileri ayarlanabilir.

### Sıfırdan Array Oluşturma

In [12]:
np.zeros((10), dtype= "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.full((3,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [16]:
np.arange(0,31,3) #0'dan 31'e kadar üçer aralıklar ile

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [18]:
np.linspace(0,1,10) #0'dan 1'e kadar 10 sayı

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [20]:
np.random.normal(10,5,(3,5)) #ortlamaı 10 standart sapması 5 

array([[18.58454149, 11.03293651, 16.08991257, 10.19042348,  6.7278265 ],
       [ 0.6277677 ,  6.21180419, 12.09547043,  4.07117818,  9.10872914],
       [18.388286  , 16.80127033, 12.85258379, 18.52148702, 13.19678568]])

In [22]:
np.random.randint(0,10,(3,5)) #0 ve 10 arasında int rastgele değerler

array([[2, 6, 4, 4, 2],
       [4, 1, 0, 9, 1],
       [8, 8, 9, 4, 3]])

In [27]:
c = np.random.randint(10, size =10)



In [48]:
c.ndim #array boyut bilgisi (vektör)
c.shape 


(10,)

In [30]:
c.shape 

(10,)

In [49]:
b = np.array([1.2,3,5,6])
b

array([1.2, 3. , 5. , 6. ])

In [36]:
c.size #içerisindeki eleman sayısı

10

In [35]:
c.dtype

dtype('int32')

In [39]:
d = np.random.randint(10,size =(3,5))
d

array([[2, 4, 9, 5, 5],
       [8, 5, 7, 7, 6],
       [3, 4, 0, 9, 2]])

In [46]:
d.ndim #matris

2

In [42]:
d.size

15

In [44]:
d.dtype

dtype('int32')

In [45]:
d.reshape((5,3))

array([[2, 4, 9],
       [5, 5, 8],
       [5, 7, 7],
       [6, 3, 4],
       [0, 9, 2]])

### Birleştirme (Concantenation)

In [3]:
a = np.array([1,2,3])
b=np.array([4,5,6])

In [5]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

###### iki boyut

In [7]:
a = np.array([[1,2,3],[4,5,6]])

In [8]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [9]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Default olarak axis = 0 alınır yani satır bazında birşetime yapılır, axis =1 dersek sütun bazına birleştirme yapılır.

### Array Ayırma (Splitting)

In [11]:
x = np.array([1,2,3,4,5,6,7,8,8])

In [13]:
np.split(x,[3,5])

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8, 8])]

0'dan 2. indexe kadar, 3. inexten 5'e kadar ve 5. indexten sonrası lacak şekilde ayrıldı.

##### iki boyut

In [15]:
m = np.arange(16).reshape(4,4)

In [16]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [21]:
ust , alt =  np.vsplit(m, [2])

In [22]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Sıralama (Sorting)

In [24]:
y = np.array ([8,5,4,7,2,3,1,0])

In [25]:
np.sort(y)

array([0, 1, 2, 3, 4, 5, 7, 8])

In [26]:
y

array([8, 5, 4, 7, 2, 3, 1, 0])

!!! y arrayi sıralanmadan geldi.

In [27]:
y.sort()

In [28]:
y

array([0, 1, 2, 3, 4, 5, 7, 8])

Eğer fonksiyon kütüphaneden çağrılırsa array üzerinde bir  değişiklik olmaz

##### iki boyut

In [30]:
m = np.random.normal(20,5,(3,3))

In [32]:
m

array([[11.73467744, 20.04988864, 16.01822212],
       [27.41604954, 29.69585015, 25.8979473 ],
       [12.69560643, 25.42705119, 21.37492176]])

In [33]:
np.sort(m, axis =0) #sütun bazında 

array([[11.73467744, 20.04988864, 16.01822212],
       [12.69560643, 25.42705119, 21.37492176],
       [27.41604954, 29.69585015, 25.8979473 ]])

In [37]:
np.sort(m, axis =1) # satır bazında

array([[11.73467744, 16.01822212, 20.04988864],
       [25.8979473 , 27.41604954, 29.69585015],
       [12.69560643, 21.37492176, 25.42705119]])